### ISSUE TITLE
Wrong unit for runway visual range

### ISSUE THREAD

**Issue by sfo** [python-metar/python-metar#107]
Consider the following METAR report:

> METAR EBBR 040220Z VRB01KT 0150 R25L/1200N R25R/0600N R02/P1500N FG BKN001 07/06 Q1017 NOSIG=

It says, that RVR for runways 25L is 1200 **m**, for 25R is 600 **m**, and for 02 is 1500 **m**, respectively.
However, the output of the following code gives the same values but with unit _feet_, which is wrong, since the METAR report gives _meters_.

```python
from metar import Metar

m = Metar.Metar('METAR EBBR 040220Z VRB01KT 0150 R25L/1200N R25R/0600N R02/P1500N FG BKN001 07/06 Q1017 NOSIG')
print(m.runway_visual_range())
```

> on runway 25L, 1200 feet; on runway 25R, 600 feet; on runway 02, greater than 1500 feet

Similarly, requesting RVR in unit _meters_ explicitly give wrong values:

```python
for name, low, high, unit in m.runway:
    print(f"RVR for runway {name}: {low.value(units='M')} m")
```

> RVR for runway 25L: 365.7599882956804 m
> RVR for runway 25R: 182.8799941478402 m
> RVR for runway 02: 457.1999853696005 m

**Comment by phobson** [comment]
Are we sure that meters are the proper default units for the RVR? Poking around, it seems like feet are the default units and perhaps there's an issue with the construction of this report.

See section 7.5.2 here
https://www.ofcm.gov/publications/fmh/FMH1/FMH1.pdf

Would be very happy to read other references that state otherwise.

**Comment by sfo** [comment]
Section 12.6.7 of the referred document also states:
> RVR shall be coded in the format RD<sub>R</sub>D<sub>R</sub>/V<sub>R</sub>V<sub>R</sub>V<sub>R</sub>V<sub>R</sub>FT, where R indicates that the runway number follows, D<sub>R</sub>D<sub>R</sub> is the runway number (an additional D<sub>R</sub> may be used for runway approach directions, such as R for right, L for left, and C for center), V<sub>R</sub>V<sub>R</sub>V<sub>R</sub>V<sub>R</sub> is the constant reportable value, and FT indicates that units of measurement are feet.

Even though the OFCM document says that RVR is usually given in feet, the unit nonetheless has to be specified explicitly in the report. Therefore, omitting the unit implies that the values are in meters.

Additionally, in the [Manual of Codes](https://library.wmo.int/doc_num.php?explnum_id=10235), page A-30, section 15.7 states:
> Note: The coding of runway visual range is based on the use of the metre in accordance with the unit specified in ICAO Annex 5

**Comment by phobson** [comment]
Thanks for digging that up

**Comment by akrherz** [comment]
PR has been merged.
