### ISSUE TITLE
ParserError for RVR field of the form R25/4999

### ISSUE THREAD

**Issue by sfo** [python-metar/python-metar#108]
Consider the following METAR report:
> METAR EBBR 172150Z 11008KT 2000 -SN BR FEW003 BKN006 M03/M04 Q1007 R25/4999 R02/4999// R75/290066

Parsing this report raises the following error:

> ParserError: Unparsed groups in body 'R25/4999' while processing 'METAR EBBR 172150Z 11008KT 2000 -SN BR FEW003 BKN006 M03/M04 Q1007 R25/4999 R02/4999// R75/290066'

However, an RVR of the form 'R25/4999' is totally valid and should be parsed without error.

**Comment by ikg1hd** [comment]
Hi Stanley,

`R25/4999` is unlikely to be an RVR. First of all, an RVR of 4999 seems rather high for `2000 -SN BR FEW003 BKN006`.
Additionally, according to the [WMO Publication No. 306 - Manual On Codes - Volume I.1 - Part A](https://community.wmo.int/activity-areas/wmo-codes/manual-codes/volume-i1):
- the correct position for an RVR is after the visibility
- an RVR should only be reported if below 1500 metres
- the RVR value should be reported in steps of 100 metres when the runway visual range is more than 800 metres

But if you append 2 slashes to `R25/4999`, it would be a runway state group in its correct position, and this group and the 2 following groups would give the complete picture for the states of all runways: 07R/25L and 02/20 are not in use, while 25R has wet and water patches, 51-100 % of runway covered, deposit depth <1 mm, friction coefficient: 0.66.

If month and year of the observation would be known, the reports before and after this one could be checked as well.

Kind regards
Thomas

**Comment by sfo** [comment]
After working with METAR for a while now and processing lots of erroneous report, I agree with @ikg1hd that this is just yet another ill-formed report, and not a problem with the parser. Therefore, I'll close this issue.
