### ISSUE TITLE
Error in Haversine formula at position class in Datatypes.py

### ISSUE THREAD

**Issue by diego-garro** [python-metar/python-metar#109]
Correct formula is:

```
a = sin(0.5(lat2 - lat1)) * sin(0.5(lat2 - lat1)) + cos(lat1) * cos(lat2) * sin(0.5 * (long2 - long1)) * sin(0.5 * (long2 - long1))
```

**Comment by akrherz** [comment]
Thanks for raising an issue.  Are you able to submit a Pull Request with the suggested change?

**Comment by diegogarromolina** [comment]
I'am able, in a few hours when arrive to my house. Thank you for the chance of colaborate.
