### ISSUE TITLE
release planning?

### ISSUE THREAD

**Issue by jdkloe** [python-metar/python-metar#126]
While following this project I see a lot of activity lately, thanks for all your work!
However, the latest release 1.7 is almost 2 years old now.
Are there plans to create a new release? Or more general, is there a release planning for this project?

**Comment by akrherz** [comment]
We are very informal here and just go as folks want to do work.  A release sounds good to me and lets see if we can resolve the one active PR yet #117 first.

**Comment by jdkloe** [comment]
Thanks for your answer. I think especially for those who only use pypi/pip it would be nice to have access to the latest improvements.
But there is no hurry at all on y side, so no problem if you wish to work on open PRs or other issues first.
