### ISSUE TITLE
Wind Speeds default to m/s when units are not provided

### ISSUE THREAD

**Issue by akrherz** [python-metar/python-metar#139]
For example

```python
from metar import Metar
m = Metar.Metar(" KDSM 310507Z COR 34026G45 2SM +TSRA SCT018 BKN023CB BKN041 21/17 A2991 "
"RMK AO2 PK WND 36051/0458 LTG DSNT W-NE RAB06 CONS LTGICCGCC OHD-W-N TS "
"OHD-W-N MOV SE P0000 T02060167")
print(m.wind_gust)
# 45 mps
```

FMH1  12.6.5 The wind group shall always end with KT to indicate that wind speeds are reported in knots.

The code `Datatypes/speed` presently defaults to MPS when units are not provided.  Perhaps we should default to knots?  Thoughts?

**Comment by tomp** [comment]
If there's a generally recognized default unit, we should use that, but I
doubt that it's knots.  I haven't tried to keep up to date on this stuff,
but the WMO guide I had when originally building this said,

The unit of wind speed used is determined by national decision. However,
the primary unit
prescribed in ICAO Annex 5 for wind speed is the kilometre per hour (KMH),
with the knot (KT)
permitted for use as a non-SI alternative unit until a termination date is
decided — subject to a
decision which is currently under review by ICAO.
(WMO-406 1995)

KMH sounds reasonable as a default, to me, unless we can convince ourselves
that most people out there consider knots the default.

**Comment by akrherz** [comment]
Thanks for chiming in @tomp.  I realize we have conflicting standards here.

1) US NWS FMH1 which mandates `KT`
2) WMO 306 / FM15 METAR which mandates `MPS` (15.5.1 2 ) The primary unit prescribed in ICAO Annex 5 for wind speed is the metre per second (MPS), with the knot (KT) permitted for use as a non-SI alternative unit until a termination date is
decided.)

I am inclined to make the default `KT` for any 3-char site ids or 4-char site ids starting with `K`.  Would that be a reasonable compromise?

**Comment by tomp** [comment]
That sounds reasonable.
