### ISSUE TITLE
Unparsed group 'WS RWY150'

### ISSUE THREAD

**Issue by christophermclement** [python-metar/python-metar#145]
from 2021-09-04 CYOW

`CYOW 040300Z 28006KT 15SM SKC 14/12 A3004 WS RWY150 RMK SLP176`

I'm inferring they mean "wind shear on runway 150?"

**Comment by sfo** [comment]
There are multiple issues with the report:
- Runway identifiers are always 2 digits, there is nothing like a runway 150.
- CYOW has 6 runways: 04/22, 07/25, 14/32, but nothing like 15 or 50. There seems to be a non-trivial typo in the report.

So that's not a bug of the parser.

**Comment by christophermclement** [comment]
Good catch. I'll hand-fix it to read "WS RWY25," as it's the best guess I've got, and it's not especially relevant to my purposes. There's no other mention in the day's METARs or TAFs of any wind shear.
