### ISSUE TITLE
Unparsed groups in body 'SKY OBS'

### ISSUE THREAD

**Issue by bushairmt** [python-metar/python-metar#181]
While processing the message METAR VIPK 130830Z 26004KT 1100 BR SKY OBS 10/07 Q1020 NOSIG Below error is displaying. 

metar.Metar.ParserError: Unparsed groups in body 'SKY OBS' while processing 'METAR VIPK 130830Z 26004KT 1100 BR SKY OBS 10/07 Q1020 NOSIG'

**Comment by akrherz** [comment]
@bushairmt , do you believe that to be valid METAR encoding?  You can pass the `strict=False` argument to the METAR parser to have it recover in this situation.

**Comment by bushairmt** [comment]
@akrherz Yes. This code is valid. "SKY OBS" is using for sky obscured condition.

**Comment by akrherz** [comment]
@bushairmt you have a link documenting that?

**Comment by bushairmt** [comment]
@akrherz  I apologise for any confusion. The code "SKY OBS" is specifically designed for use exclusively in our country and does not adhere to international standards. As you suggested strict=False argument solves my issues. Thus this issue may be marked closed.
