### ISSUE TITLE
test/all_tests.py missing in tarfile on pypi

### ISSUE THREAD

**Issue by jdkloe** [python-metar/python-metar#29]
you have chosen to include only part of this repository in the tar file published on pypi.
However, the included README file refers to the test/all_tests.py  file, and that one is missing.
Please provide this file in your next update.
It might be easier to provide the full content of this repository in the tar file published on pypi.

**Comment by jdkloe** [comment]
the same holds for the sample files parse_metar.py, get_report.py and sample.py. They are also not present in the tarfile on pypi but are mentioned in the provided README file.

**Comment by akrherz** [comment]
For reference here, the current `python-metar-1.4.0` file on pypi has
```text
python-metar-1.4.0/
python-metar-1.4.0/sample.py
python-metar-1.4.0/PKG-INFO
python-metar-1.4.0/test/
python-metar-1.4.0/test/test_temperature.py
python-metar-1.4.0/test/test_metar.py
python-metar-1.4.0/test/test_distance.py
python-metar-1.4.0/test/test_direction.py
python-metar-1.4.0/test/test_speed.py
python-metar-1.4.0/test/all_tests.py
python-metar-1.4.0/test/test_pressure.py
python-metar-1.4.0/parse_metar.py
python-metar-1.4.0/setup.py
python-metar-1.4.0/NOTES
python-metar-1.4.0/CHANGES
python-metar-1.4.0/metar/
python-metar-1.4.0/metar/__init__.py
python-metar-1.4.0/metar/Datatypes.py
python-metar-1.4.0/metar/Metar.py
python-metar-1.4.0/get_report.py
```

I'll have a PR shortly updating this
