### ISSUE TITLE
download location WMO Manual on Codes, vol I.1, Part A 

### ISSUE THREAD

**Issue by jdkloe** [python-metar/python-metar#30]
In the README file you write:

I'm not sure from where you can download the World Meteorological
Organization (WMO) Manual on Codes, vol I.1, Part A (WMO-306 I.i.A)

This manual can be found through the WMO website:
http://www.wmo.int/pages/prog/www/WMOCodes.html
or downloaded directly via
https://library.wmo.int/opac/doc_num.php?explnum_id=3361

**Comment by akrherz** [comment]
@jdkloe appears that 7e9d76f addressed this for you.

**Comment by jdkloe** [comment]
ok, thanks for noting this.
