### ISSUE TITLE
Feet vs. Meters

### ISSUE THREAD

**Issue by gliesian-llc** [python-metar/python-metar#40]
This METAR has R28L/2600FT but reduction reads:

visual range: on runway 28L, 2600 meters
(should read: visual range: on runway 28L, 2600 feet)

Reference: METAR KPIT 091955Z COR 22015G25KT 3/4SM R28L/2600FT TSRA OVC010CB 18/16 A2992 RMK SLP045 T01820159

**Comment by maxdow** [comment]
When running the test on this case, it still fail because there is not unit conversion, am i right ?

**Comment by akrherz** [comment]
@maxdow I am unsure if I am following your statement. Could you kindly elaborate?

**Comment by maxdow** [comment]
...oups sorry my bad , my test was running with 1.2 version.. 😌
