### ISSUE TITLE
Straighten out what version python-metar is!

### ISSUE THREAD

**Issue by akrherz** [python-metar/python-metar#50]
Depending on where you look in the source code, python-metar is either at version 1.2, 1.4 or 1.5.0.

On pypi, python-metar is at 1.4.0
conda-forge metar is at 1.5.0
I have various github issues against a 1.5.0 milestone, hehe.

We should at least straighten out how the version is specified.  My thought is to define it once in `metar/__init__.py` and then reference that in `setup.py` and perhaps in `metar/Metar.py` (perhaps it should be removed from that file).

Maybe our first formal release should be `1.5.1` ?

**Comment by phobson** [comment]
Can we pump the brakes on the release for a few days? I think I'll have a PR for #51 in a few days.

**Comment by akrherz** [comment]
@phobson no worries at all on waiting.  Thank you.
