### ISSUE TITLE
Allow `ParserErrors` to not raise

### ISSUE THREAD

**Issue by phobson** [python-metar/python-metar#51]
If you're like me and get most of your METAR codes from FAA's ASOS program, you get a *lot* of parser errors.

The `MetarParser` subclass in [cloudside](https://github.com/Geosyntec/cloudside/blob/master/cloudside/station.py#L149) gets around this by simply logging the error and moving on. 

It'd be nice to have this as an *option* upstream.

**Comment by akrherz** [comment]
The most recent release of `python-metar` can raise `ParserError` on two conditions

1. Some unexpected exception happens while parsing
2. There are portions of the METAR that were not parsed.

We gook a change with ce290c2 that added a `strict` option to the Metar constructor that allows the ParserError not to raise in the case of 2 above.  The question is if `strict` should be extended to cover 1 or not.  Or replaced with another option as suggested in this ticket.

My first opinion is that blanket `Exception` catching should never happen.  Tests and code hardening should prevent issues like this from happen.  The `try` block is also too large.  This is one of the things I had in mind to address in a later release.  Removing it now would likely end in tears.  Allthough, I have a database millions of real US and global METARs that could be sent through as a smoke test for such a change.

I think my preference here, in-lieu of making a release, is just to extend `strict` to cover 1 above.

Thoughts?
