### ISSUE TITLE
whitespace/code style issue

### ISSUE THREAD

**Issue by phobson** [python-metar/python-metar#54]
While I hesitate to even bring this up, the mix of 2-space and 4-space indentation makes the code base a little tricky to work with.

I propose we standardize to 4 spaces, and remove all of the trailing white space in that process.

I would also suggest that we address other PEP8-ish issues, but separately from the indentation.

**Comment by akrherz** [comment]
Indeed, let us do something crazy and run [python black](https://github.com/ambv/black) over the code base.

**Comment by phobson** [comment]
FYI, I just ran black in a new branch and 0_o it is magic

**Comment by akrherz** [comment]
So I am having some second thoughts on just running `black` over the code.  It is very opinionated on how things should be, not saying it wrong.  Seems like this would set a rather high contribution bar as we'd then need to have a code style check that enforces this going forward.

Standardizing on 4 space indent was a MUST in my opinion and also removing the trailing whitespace, which I think are both done now.

@phobson you want to itemize more things to do here or just close this and open new issues / PRs as future whitespace things comes up?

**Comment by phobson** [comment]
Yeah, black is a little heavy-handed. I'm definitely not married to the idea.

I agree that the 4-space issue was absolutely necessary. Now that that's done, I think we can upgrade the code style more organically, though I wouldn't oppose systematic changed other pep8 big fish like spaces after (but not before) commas, white space around brackets. 

But I think even those things can be fixed as more of the code base gets touched/updated.
