### ISSUE TITLE
failing test case

### ISSUE THREAD

**Issue by jdkloe** [python-metar/python-metar#60]
Although the unit testing at travis runs without problem, another way of testing actually fails:
`python3 setup.py test`
produces this error:
======================================================================
ERROR: Station (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: Station
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/jos/python-metar-master/metar/Station.py", line 8, in <module>
    from datatypes import position, distance, direction
ModuleNotFoundError: No module named 'datatypes'
======================================================================
and looking at the source code I think it is right, this sure seems a mistake to me in the Station.py file.
This is the case for the current git version and also in the 1.6.0 release version.

In addition, it may be good to activate this way of testing as well on travis, or change the code to let the nose testing execute this test.

**Comment by akrherz** [comment]
I believe this work is done, but interestingly the example command does not run any tests
```
$ python3 setup.py test
running test
running egg_info
writing metar.egg-info/PKG-INFO
writing dependency_links to metar.egg-info/dependency_links.txt
writing top-level names to metar.egg-info/top_level.txt
reading manifest file 'metar.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'metar.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

Have added this as a TODO item on the pytest ticket #70 and will close this one now.
