### ISSUE TITLE
Parse error on METAR COR

### ISSUE THREAD

**Issue by maxdow** [python-metar/python-metar#62]
This METAR  `METAR COR ESNS 141420Z 10007KT 9999 FEW045TCU SCT047 14/06 Q1010=` fail `metar.Metar.ParserError: Unparsed groups in body: ESNS 141420Z` because of the group "METAR COR" . 

![image](https://user-images.githubusercontent.com/711050/45819857-acf3ed80-bce5-11e8-97fa-7f80a19bcef7.png)

ref : http://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI1/Publications/2014update/306_vol_I1_2014_en_track.pdf

By the way, thanks for this great lib :)

**Comment by tomp** [comment]
"METAR COR" indicates a corrected observation.  It should replace the
previously reported observation for that station and time.
We might want to parse that out and keep track of it, but we could also
just teach the module to ignore it.

**Comment by tomp** [comment]
Looking at the docs, I noticed that the "COR" code is also included in the US METAR spec, but according to that, it's supposed to be located after the time stamp, and before the wind group, in the location where "AUTO" is inserted for automatically recorded observations.  The code should already parse it correctly if it's in that location.  It looks like we will need to support this alternative, as well.

**Comment by alko05** [comment]
Using Metar 1.6.0, a KCOS METAR gives the parse error
KCOS 070954Z COR VRB06KT 10SM FEW100 SCT180 BKN210 M08/M11 A3015 RMK AO2 SLP271 T10781111
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/metar/Metar.py", line 452, in __init__
    raise ParserError(message)
metar.Metar.ParserError: Unparsed groups in body 'KCOS_1207.txt:KCOS' while processing 'KCOS_1207.txt:KCOS 070954Z COR VRB06KT 10SM FEW100 SCT180 BKN210 M08/M11 A3015 RMK AO2 SLP271 T10781111'

**Comment by tomp** [comment]
`KCOS_1207.txt:` is not part of the METAR report.  You need to strip this
off before passing the report to the Metar decoder.

Tom
