### ISSUE TITLE
AC code should be added to CLOUD_TYPE

### ISSUE THREAD

**Issue by maxdow** [python-metar/python-metar#64]
Hi,

in this METAR `METAR LOXZ 141420Z 08006KT 20KM VCSH FEW025SC SCT040SC BKN090AC 21/14 Q1015 BECMG SCT090` parsing is ok but when we want the string representation we got an error 
```
line 1161, in sky_conditions
    what = CLOUD_TYPE[cloud]
KeyError: 'AC'
```  

AC for Alto Cumulus should be added.

**Comment by akrherz** [comment]
Thank you, will fix this as per [WMO Cloud Atlas](https://cloudatlas.wmo.int/abbr-and-symbols-of-clouds-table-genera-species.html), but the label for your example is 'Altocumulus'
