### ISSUE TITLE
ASOS 5 minute data

### ISSUE THREAD

**Issue by spmacdonald** [python-metar/python-metar#74]
Not sure if this is out of scope for this project but I am trying to parse the ASOS 5 minute records which look like:

`23061KALS ALS20180827181010908/27/18 18:10:31  5-MIN KALS 280110Z AUTO 24012KT 10SM CLR 23/02 A3009 7380 25 9900 230/12 RMK AO2 T02280022`

The parts after the `5-MIN` look almost like a METAR string but not quite?  Just wondering if this would be the right place to support parsing this data?

The only specification documentation I can find is here, ftp://ftp.ncdc.noaa.gov/pub/data/asos-fivemin/td6401b.txt

Thank you for your time.

**Comment by akrherz** [comment]
@spmacdonald thanks for reaching out!  I would certainly see adding a helper method to push these obs properly through our library.  The nice aspect of these files are that the year and month timestamps are included, which could then be used to remove ambiguity when parsing the raw METAR timestamp.  I think I could try generating something for your commentary in the coming future, or if you wanted to PR something, that would be great.  We would definitely not wish to support sending the entire string to the METAR parser, but have the helper method split the string and make the magic happen.

**Comment by spmacdonald** [comment]
Hey thanks for the quick reply.

Munging that string into something python-metar can parse was my idea too, unfortunately it seems more difficult than just slicing the string and prepending `METAR`:

```
'METAR KALS 280110Z AUTO 24012KT 10SM CLR 23/02 A3009 7380 25 9900 230/12 RMK AO2 T02280022'
>>> Metar.Metar(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/venv/lib/python3.5/site-packages/metar/Metar.py", line 452, in __init__
    raise ParserError(message)
metar.Metar.ParserError: Unparsed groups in body '25 230/12' while processing 'METAR KALS 280110Z AUTO 24012KT 10SM CLR 23/02 A3009 7380 25 9900 230/12 RMK AO2 T02280022'
```

Is this what you had in mind?

**Comment by akrherz** [comment]
@spmacdonald Oye, I didn't realize that the METARs themselves may be poorly formed.  Will have to research this some more, but you can do pass the `strict=False` argument to the parser to get whatever data it can.
```Metar.Metar(s, strict=False)```

**Comment by spmacdonald** [comment]
Ok thanks! That seems to work:

```
>>> print(Metar.Metar('METAR KORD 011020Z 36003KT 9SM CLR 21/17 A2980 790 78 1700 360/03 RMK AO2 T02110172', strict=False).string())
/home/vagrant/venv/lib/python3.5/site-packages/metar/Metar.py:454: RuntimeWarning: Unparsed groups in body '78 360/03' while processing 'METAR KORD 011020Z 36003KT 9SM CLR 21/17 A2980 790 78 1700 360/03 RMK AO2 T02110172'
  warnings.warn(message, RuntimeWarning)
station: KORD
type: routine report, cycle 10 (automatic report)
time: Thu Nov  1 10:20:00 2018
temperature: 21.1 C
dew point: 17.2 C
wind: N at 3 knots
visibility: 9 miles
pressure: 1700.0 mb
sky: clear
remarks:
- Automated station (type 2)
METAR: METAR KORD 011020Z 36003KT 9SM CLR 21/17 A2980 790 78 1700 360/03 RMK AO2 T02110172
```

It looks like the extra fields are relative humidity and density altitude, maybe others?  

Thanks a lot for your help
