### ISSUE TITLE
Auto remove = and end of standard METAR

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [python-metar/python-metar#84]
Hi!

thanks for providing the METAR python package!

I understand every METAR ends with a "=". I was wondering if one could include an autoremove of this as else an error is reported?

'METAR EGLC 010020Z AUTO 19004KT 150V220 9999 NCD 17/13 Q1022='

Best

Georg

**Comment by akrherz** [comment]
Thanks for the feedback, this seems like a reasonable request.
