### ISSUE TITLE
Pandas - Reindex issue.

### ISSUE THREAD

**Issue by rajun897** [python-metar/python-metar#88]
Hello,

 I am using the Pandas package for my robot framework implementation.
 My scenario is to get the data from excel and prepared the below .py file:

import pandas as pd
from pandas import ExcelFile

class excelpd(object):
    def __init__(self, pathtofile, sheetname):
        print("Setting up File path and sheet name.")
        self.df = pd.read_excel(pathtofile, sheet_name=sheetname)           
    
    def get_colw(self,rowname,name):
        if rowname == "Login":
            LoginData = self.df.reindex([1 , 2])
            column = LoginData[name]
            print(column)
            return(column)
        if rowname == "Part":
            PartData = self.df.reindex([4 , 5])
            column = PartData[name]
            print(column)
            return(column)

and Calling the function by passing the parameters as below:
 Get Colw    Login    Username

Giving error message as "KeyError: 'PartName'.

Could you please help me to resolve the issue.

Attached the file using for the test.

![image](https://user-images.githubusercontent.com/47881039/54899684-a34a7d00-4ef6-11e9-85b9-8f0b0617804b.png)

**Comment by akrherz** [comment]
Nothing to do with our project, please see [pandas](https://github.com/pandas-dev/pandas)
