### ISSUE TITLE
Historical METAR

### ISSUE THREAD

**Issue by debenson11** [python-metar/python-metar#89]
I have historical METARs to parse going back several years.  Is there a way I can import and tell the import the month/year that the METAR originated?

**Comment by akrherz** [comment]
When you pass a METAR string to `Metar.Metar()`, you can also pass `year` and `month` like so

```
>>> report = Metar.Metar("KEWR 101651Z", year=2000, month=3)
>>> report.time
datetime.datetime(2000, 3, 10, 16, 51)
``

**Comment by debenson11** [comment]
Thank you so much, sorry I missed that.

David Benson
Debenson11@gmail.com     
(614)271-6613
